import { AppError } from "../../utils/app-error.js";
import { allocatedCapacity,countActiveValidTicketTypes,deleteTicketType,findInventoryEvent,findTicketType,insertTicketType,listTicketTypes,setTicketSalesStatus,updateDraftTicketType } from "./admin-ticket-types.repository.js";
import type { CreateTicketTypeInput,UpdateTicketTypeInput } from "./admin-ticket-types.schema.js";

type Row=NonNullable<Awaited<ReturnType<typeof findTicketType>>>;
const map=(row:Row)=>({id:row.id,eventId:row.event_id,name:row.name,description:row.description,price:Number(row.price),capacity:row.capacity,reservedQuantity:row.reserved_quantity,soldQuantity:row.sold_quantity,availableQuantity:row.capacity-row.reserved_quantity-row.sold_quantity,maxPerOrder:row.max_per_order,salesStartAt:row.sales_start_at,salesEndAt:row.sales_end_at,isActive:Boolean(row.is_active),createdAt:row.created_at,updatedAt:row.updated_at});
async function eventOrFail(id:number){const event=await findInventoryEvent(id);if(!event)throw AppError.notFound("Event not found","EVENT_NOT_FOUND");return event;}
function validateWindow(start:string|null|undefined,end:string|null|undefined,eventEnd:Date){if(start&&end&&new Date(end)<=new Date(start))throw AppError.badRequest("Ticket sales end must be after sales start","INVALID_TICKET_SALES_WINDOW");if(end&&new Date(end)>eventEnd)throw AppError.badRequest("Ticket sales cannot end after the Event ends","TICKET_SALES_AFTER_EVENT_END");}
async function validateAllocation(eventId:number,capacity:number,excludeId?:number){const event=await eventOrFail(eventId);if(event.venue_capacity&&await allocatedCapacity(eventId,excludeId)+capacity>event.venue_capacity)throw new AppError(409,"Ticket Type capacity would exceed Event venue capacity","EVENT_CAPACITY_EXCEEDED");return event;}
export async function getTicketTypeList(eventId:number){await eventOrFail(eventId);return (await listTicketTypes(eventId)).map(map);}
export async function createTicketType(input:CreateTicketTypeInput){const event=await validateAllocation(input.eventId,input.capacity);if(["completed","cancelled"].includes(event.status)||event.end_time<=new Date())throw new AppError(409,"New Ticket Types cannot be added to a closed Event","EVENT_CLOSED");validateWindow(input.salesStartAt??event.sales_start_at?.toISOString(),input.salesEndAt??event.sales_end_at?.toISOString(),event.end_time);const safeInput=event.status==="draft"?input:{...input,isActive:false};try{return map((await findTicketType(await insertTicketType(safeInput)))!);}catch(error){if((error as {code?:string}).code==="ER_DUP_ENTRY")throw new AppError(409,"This Event already has a Ticket Type with that name","DUPLICATE_TICKET_TYPE");throw error;}}
export async function updateTicketType(id:number,input:UpdateTicketTypeInput){const current=await findTicketType(id);if(!current)throw AppError.notFound("Ticket Type not found","TICKET_TYPE_NOT_FOUND");const event=await eventOrFail(current.event_id);if(["completed","cancelled"].includes(event.status))throw new AppError(409,"Ticket inventory is read-only for this Event","TICKET_TYPE_LOCKED");const committed=current.reserved_quantity+current.sold_quantity;const capacity=input.capacity??current.capacity;if(event.status!=="draft"&&capacity<current.capacity)throw new AppError(409,"Ticket capacity may not decrease after the Event is published","CAPACITY_CANNOT_DECREASE");if(capacity<committed)throw new AppError(409,"Capacity cannot be below reserved plus sold quantity","CAPACITY_BELOW_COMMITTED");if(event.status!=="draft"&&input.price!==undefined&&input.price!==Number(current.price)){if(committed>0)throw new AppError(409,"Price cannot change after a Ticket Type has reserved or sold inventory; pause it and create a new price tier","PRICE_LOCKED_BY_ORDERS");if(current.is_active)throw new AppError(409,"Pause this Ticket Type before changing its price","PAUSE_BEFORE_PRICE_CHANGE");}await validateAllocation(current.event_id,capacity,current.id);validateWindow(input.salesStartAt===undefined?(current.sales_start_at??event.sales_start_at)?.toISOString():input.salesStartAt,input.salesEndAt===undefined?(current.sales_end_at??event.sales_end_at)?.toISOString():input.salesEndAt,event.end_time);const safeInput=event.status==="draft"?input:{...input,isActive:undefined};await updateDraftTicketType(id,safeInput);return map((await findTicketType(id))!);}
export async function changeTicketSalesStatus(id:number,active:boolean){const ticket=await findTicketType(id);if(!ticket)throw AppError.notFound("Ticket Type not found","TICKET_TYPE_NOT_FOUND");const event=await eventOrFail(ticket.event_id);if(!["published","ongoing"].includes(event.status))throw new AppError(409,"Sales can only be paused or resumed for a published or ongoing Event","EVENT_NOT_ON_SALE");if(active){if(ticket.capacity<=ticket.reserved_quantity+ticket.sold_quantity)throw new AppError(409,"Sold-out Ticket Type cannot resume sales","TICKET_TYPE_SOLD_OUT");const now=new Date();const end=ticket.sales_end_at??event.sales_end_at;if(event.end_time<=now)throw new AppError(409,"Event sales are closed","SALES_ENDED");if(end&&now>end)throw new AppError(409,"Ticket sales window has ended","SALES_ENDED");}else if(event.visibility==="visible"&&ticket.is_active&&await countActiveValidTicketTypes(ticket.event_id,ticket.id)<1){throw new AppError(409,"Hide the Event or activate another Ticket Type before pausing the final active tier","LAST_ACTIVE_TICKET_TYPE");}await setTicketSalesStatus(id,active);return map((await findTicketType(id))!);}
export async function removeTicketType(id:number){const ticket=await findTicketType(id);if(!ticket)throw AppError.notFound("Ticket Type not found","TICKET_TYPE_NOT_FOUND");const event=await eventOrFail(ticket.event_id);const committed=ticket.reserved_quantity+ticket.sold_quantity;if(["completed","cancelled"].includes(event.status)||committed>0)throw new AppError(409,"Ticket Type has committed inventory and cannot be deleted; pause sales instead","TICKET_TYPE_HAS_ORDERS");if(event.status!=="draft"&&ticket.is_active)throw new AppError(409,"Pause this Ticket Type before deleting it","PAUSE_BEFORE_DELETE");if(["published","ongoing"].includes(event.status)&&event.visibility==="visible"&&await countActiveValidTicketTypes(ticket.event_id,ticket.id)<1)throw new AppError(409,"A visible published Event must retain at least one active valid Ticket Type; hide the Event or activate another tier first","LAST_TICKET_TYPE_REQUIRED");if(!await deleteTicketType(id))throw new AppError(409,"Ticket Type has related Orders and cannot be deleted","TICKET_TYPE_HAS_ORDERS");}
