import type { ResultSetHeader,RowDataPacket } from "mysql2/promise";
import { pool } from "../../database/pool.js";
import type { CreateTicketTypeInput,UpdateTicketTypeInput } from "./admin-ticket-types.schema.js";

export interface TicketTypeRow extends RowDataPacket{id:number;event_id:number;name:string;description:string|null;price:string;capacity:number;reserved_quantity:number;sold_quantity:number;max_per_order:number;sales_start_at:Date|null;sales_end_at:Date|null;is_active:number;created_at:Date;updated_at:Date}
export interface InventoryEventRow extends RowDataPacket{id:number;name:string;status:"draft"|"published"|"ongoing"|"completed"|"cancelled";visibility:"visible"|"hidden";venue_capacity:number|null;start_time:Date;end_time:Date;sales_start_at:Date|null;sales_end_at:Date|null}
const select="id,event_id,name,description,price,capacity,reserved_quantity,sold_quantity,max_per_order,sales_start_at,sales_end_at,is_active,created_at,updated_at";
const dbDate=(value:string|null|undefined)=>value==null?value:new Date(new Date(value).getTime()+7*3600000).toISOString().slice(0,23).replace("T"," ");
export async function listTicketTypes(eventId:number){const [rows]=await pool.query<TicketTypeRow[]>(`SELECT ${select} FROM ticket_types WHERE event_id=? ORDER BY price,id`,[eventId]);return rows;}
export async function findTicketType(id:number){const [rows]=await pool.query<TicketTypeRow[]>(`SELECT ${select} FROM ticket_types WHERE id=? LIMIT 1`,[id]);return rows[0]??null;}
export async function findInventoryEvent(id:number){const [rows]=await pool.query<InventoryEventRow[]>("SELECT id,name,status,visibility,venue_capacity,start_time,end_time,sales_start_at,sales_end_at FROM events WHERE id=? LIMIT 1",[id]);return rows[0]??null;}
export async function allocatedCapacity(eventId:number,excludeId?:number){const [rows]=await pool.query<RowDataPacket[]>(`SELECT COALESCE(SUM(capacity),0) total FROM ticket_types WHERE event_id=?${excludeId?" AND id<>?":""}`,excludeId?[eventId,excludeId]:[eventId]);return Number(rows[0]?.total??0);}
export async function countActiveValidTicketTypes(eventId:number,excludeId?:number){const [rows]=await pool.query<RowDataPacket[]>(`SELECT COUNT(*) total FROM ticket_types WHERE event_id=? AND is_active=TRUE AND capacity>0 AND max_per_order>0${excludeId?" AND id<>?":""}`,excludeId?[eventId,excludeId]:[eventId]);return Number(rows[0]?.total??0);}
export async function insertTicketType(input:CreateTicketTypeInput){const [result]=await pool.execute<ResultSetHeader>("INSERT INTO ticket_types(event_id,name,description,price,capacity,max_per_order,sales_start_at,sales_end_at,is_active) VALUES(?,?,?,?,?,?,?,?,?)",[input.eventId,input.name,input.description??null,input.price,input.capacity,input.maxPerOrder,dbDate(input.salesStartAt)??null,dbDate(input.salesEndAt)??null,input.isActive]);return result.insertId;}
export async function updateDraftTicketType(id:number,input:UpdateTicketTypeInput){const map:Record<string,string|number|boolean|null|undefined>={name:input.name,description:input.description,price:input.price,capacity:input.capacity,max_per_order:input.maxPerOrder,sales_start_at:dbDate(input.salesStartAt),sales_end_at:dbDate(input.salesEndAt),is_active:input.isActive};const sets:string[]=[];const values:(string|number|boolean|null)[]=[];for(const [key,value] of Object.entries(map)){if(value!==undefined){sets.push(`${key}=?`);values.push(value);}}if(sets.length)await pool.execute(`UPDATE ticket_types SET ${sets.join(",")} WHERE id=?`,[...values,id]);}
export async function increasePublishedCapacity(id:number,capacity:number){await pool.execute("UPDATE ticket_types SET capacity=? WHERE id=? AND capacity<=?",[capacity,id,capacity]);}
export async function setTicketSalesStatus(id:number,active:boolean){await pool.execute("UPDATE ticket_types SET is_active=? WHERE id=?",[active,id]);}
export async function deleteTicketType(id:number){const [references]=await pool.query<RowDataPacket[]>("SELECT COUNT(*) total FROM order_items WHERE ticket_type_id=?",[id]);if(Number(references[0]?.total??0)>0)return false;const [result]=await pool.execute<ResultSetHeader>("DELETE FROM ticket_types WHERE id=?",[id]);return result.affectedRows===1;}
