import { Edit3, FolderTree, Plus, Power, Trash2, X } from "lucide-react";
import { useEffect, useState, type FormEvent } from "react";
import { createPortal } from "react-dom";
import { ApiRequestError } from "@/services/api";
import { createAdminCategory,deleteAdminCategory,listAdminCategories,updateAdminCategory,type AdminCategory } from "@/services/admin-categories.service";
import "@/styles/admin-categories.css";

const empty={name:"",slug:"",description:"",icon:"",sortOrder:"0",isActive:true};
export function AdminCategoriesPage(){
  const [items,setItems]=useState<AdminCategory[]>([]);const [form,setForm]=useState(empty);const [editing,setEditing]=useState<number|null>(null);const [open,setOpen]=useState(false);const [busy,setBusy]=useState(false);const [error,setError]=useState("");
  async function load(){try{setItems(await listAdminCategories());}catch(e){setError(e instanceof Error?e.message:"Unable to load Categories");}}
  useEffect(()=>{let active=true;void listAdminCategories().then(data=>{if(active)setItems(data);}).catch(e=>{if(active)setError(e instanceof Error?e.message:"Unable to load Categories");});return()=>{active=false;};},[]);
  function create(){setEditing(null);setForm(empty);setError("");setOpen(true);}
  function edit(item:AdminCategory){setEditing(item.id);setForm({name:item.name,slug:item.slug,description:item.description??"",icon:item.icon??"",sortOrder:String(item.sortOrder),isActive:item.isActive});setError("");setOpen(true);}
  async function submit(event:FormEvent){event.preventDefault();setBusy(true);setError("");try{const payload={name:form.name.trim(),slug:form.slug.trim().toLowerCase(),description:form.description.trim()||null,icon:form.icon.trim()||null,sortOrder:Number(form.sortOrder),isActive:form.isActive};if(editing)await updateAdminCategory(editing,payload);else await createAdminCategory(payload);setOpen(false);await load();}catch(e){setError(e instanceof ApiRequestError?e.message:"Unable to save Category");}finally{setBusy(false);}}
  async function remove(item:AdminCategory){if(!window.confirm(`Delete Category "${item.name}"?`))return;try{await deleteAdminCategory(item.id);await load();}catch(e){setError(e instanceof Error?e.message:"Unable to delete Category");}}
  async function toggle(item:AdminCategory){try{await updateAdminCategory(item.id,{isActive:!item.isActive});await load();}catch(e){setError(e instanceof Error?e.message:"Unable to update Category");}}
  return <section className="categories-page">
    <header className="categories-header"><div><span className="events-eyebrow"><FolderTree size={14}/> EVENT TAXONOMY</span><h2>Category Management</h2><p>Maintain reusable Event categories without changing application code.</p></div><button className="events-primary-button" onClick={create}><Plus size={17}/> Create Category</button></header>
    {error&&<div className="categories-error" role="alert">{error}</div>}
    <div className="categories-grid">{items.map(item=><article className={`category-admin-card ${item.isActive?"":"is-inactive"}`} key={item.id}><div><span className="category-slug">/{item.slug}</span><h3>{item.name}</h3><p>{item.description||"No description provided."}</p></div><dl><div><dt>Events</dt><dd>{item.eventCount}</dd></div><div><dt>Order</dt><dd>{item.sortOrder}</dd></div><div><dt>Status</dt><dd>{item.isActive?"Active":"Inactive"}</dd></div></dl><footer><button onClick={()=>edit(item)} title="Edit Category"><Edit3 size={16}/> Edit</button><button onClick={()=>void toggle(item)} title={item.isActive?"Deactivate Category":"Activate Category"}><Power size={16}/>{item.isActive?"Deactivate":"Activate"}</button><button className="danger" disabled={item.eventCount>0} onClick={()=>void remove(item)} title={item.eventCount>0?"Referenced Categories cannot be deleted":"Delete Category"}><Trash2 size={16}/></button></footer></article>)}</div>
    {open&&createPortal(<div className="events-dialog-backdrop"><div className="categories-dialog" role="dialog" aria-modal="true" aria-labelledby="category-dialog-title"><header><div><small>CATEGORY REGISTRY</small><h3 id="category-dialog-title">{editing?"Edit Category":"Create Category"}</h3></div><button onClick={()=>setOpen(false)} aria-label="Close"><X/></button></header><form onSubmit={submit}><label>Name *<input required minLength={2} maxLength={100} value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Slug *<input required pattern="[a-z0-9]+(-[a-z0-9]+)*" value={form.slug} onChange={e=>setForm({...form,slug:e.target.value})} placeholder="technology-events"/></label><label className="wide">Description<textarea maxLength={500} value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><label>Icon key<input maxLength={50} value={form.icon} onChange={e=>setForm({...form,icon:e.target.value})}/></label><label>Sort order<input type="number" min="0" max="10000" value={form.sortOrder} onChange={e=>setForm({...form,sortOrder:e.target.value})}/></label><label className="category-active"><input type="checkbox" checked={form.isActive} onChange={e=>setForm({...form,isActive:e.target.checked})}/> Available for new Events</label>{error&&<p className="categories-error wide">{error}</p>}<footer className="wide"><button type="button" onClick={()=>setOpen(false)}>Cancel</button><button className="primary" disabled={busy}>{busy?"Saving...":"Save Category"}</button></footer></form></div></div>,document.body)}
  </section>;
}
